### PR TITLE
fix cpu_speed for ppc64

### LINKED ISSUE #25: getting cpu speed sometimes (ppc64 / ppc64le) still fails
```
[ignatenkobrain@ppc64-test ~][PROD]$ lscpu
Architecture:        ppc64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Big Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           2
NUMA node(s):        1
Model:               2.1 (pvr 004b 0201)
Model name:          POWER8 (architected), altivec supported
Hypervisor vendor:   KVM
Virtualization type: para
L1d cache:           64K
L1i cache:           32K
NUMA node0 CPU(s):   0,1
```

there is no bogomips or mhz....

### PR DESCRIPTION
**Pull request by FillZpp**
Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>

Fixes #25

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Let me test this.

**Comment by ignatenkobrain** [comment]
This PR broke s390x architecture with:

```
---- test::test_cpu_speed stdout ----
thread 'test::test_cpu_speed' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown', src/libcore/result.rs:999:5
```

And ppc64le still has same problem.

Let me know how I can help, if I should provide some outputs from systems or anything like that.

**Comment by ignatenkobrain** [comment]
```
Architecture:        s390x
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Big Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s) per book:  1
Book(s) per drawer:  1
Drawer(s):           2
NUMA node(s):        1
Vendor ID:           IBM/S390
Machine type:        2964
CPU dynamic MHz:     5000
CPU static MHz:      5000
BogoMIPS:            3033.00
Hypervisor:          z/VM 6.4.0
Hypervisor vendor:   IBM
Virtualization type: full
Dispatching mode:    horizontal
L1d cache:           128K
L1i cache:           96K
L2d cache:           2048K
L2i cache:           2048K
L3 cache:            65536K
L4 cache:            491520K
NUMA node0 CPU(s):   0,1
Flags:               esan3 zarch stfle msa ldisp eimm dfp edat etf3eh highgprs te vx sie
```

this is s390x lscpu I believe.

```
Architecture:        ppc64le
Byte Order:          Little Endian
CPU(s):              12
On-line CPU(s) list: 0-11
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           12
NUMA node(s):        1
Model:               2.2 (pvr 004e 1202)
Model name:          POWER9 (architected), altivec supported
Hypervisor vendor:   KVM
Virtualization type: para
L1d cache:           32K
L1i cache:           32K
NUMA node0 CPU(s):   0-11
```

and this one is ppc64le…

**Comment by ignatenkobrain** [comment]
# `cat /proc/cpuinfo`

## `ppc64le`

```
processor	: 0
cpu		: POWER8 (architected), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)
processor	: 1
cpu		: POWER8 (architected), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)
processor	: 2
cpu		: POWER8 (architected), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)
processor	: 3
cpu		: POWER8 (architected), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)
timebase	: 512000000
platform	: pSeries
model		: IBM pSeries (emulated by qemu)
machine		: CHRP IBM pSeries (emulated by qemu)
MMU		: Hash
```

## `s390x`

```
vendor_id       : IBM/S390
# processors    : 2
bogomips per cpu: 3033.00
max thread id   : 0
features	: esan3 zarch stfle msa ldisp eimm dfp edat etf3eh highgprs te vx sie 
facilities      : 0 1 2 3 4 6 7 8 9 10 12 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 30 31 32 33 34 35 36 37 40 41 42 43 44 45 46 47 48 49 50 51 52 53 55 57 69 70 71 72 73 74 75 76 77 80 81 82 128 129
cache0          : level=1 type=Data scope=Private size=128K line_size=256 associativity=8
cache1          : level=1 type=Instruction scope=Private size=96K line_size=256 associativity=6
cache2          : level=2 type=Data scope=Private size=2048K line_size=256 associativity=8
cache3          : level=2 type=Instruction scope=Private size=2048K line_size=256 associativity=8
cache4          : level=3 type=Unified scope=Shared size=65536K line_size=256 associativity=16
cache5          : level=4 type=Unified scope=Shared size=491520K line_size=256 associativity=30
processor 0: version = FF,  identification = 3533E8,  machine = 2964
processor 1: version = FF,  identification = 3533E8,  machine = 2964
cpu number      : 0
cpu MHz dynamic : 5000
cpu MHz static  : 5000
cpu number      : 1
cpu MHz dynamic : 5000
cpu MHz static  : 5000
```

**Comment by FillZpp** [comment]
@ignatenkobrain It seems i should use`BogoMIPS` instead of `BogoMIPS\t`. How about now?

**Comment by ignatenkobrain** [comment]
```
+ cat /proc/cpuinfo
processor	: 0
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 1
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 2
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 3
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 4
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 5
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 6
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 7
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 8
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 9
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 10
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
processor	: 11
cpu		: POWER9 (architected), altivec supported
clock		: 2250.000000MHz
revision	: 2.2 (pvr 004e 1202)
timebase	: 512000000
platform	: pSeries
model		: IBM pSeries (emulated by qemu)
machine		: CHRP IBM pSeries (emulated by qemu)
MMU		: Radix
+ /usr/bin/env CARGO_HOME=.cargo RUSTC_BOOTSTRAP=1 /usr/bin/cargo test -j12 -Z avoid-dev-deps --release --no-fail-fast -- --skip test::test_hostname
BUILDSTDERR:        Fresh cc v1.0.37
BUILDSTDERR:        Fresh libc v0.2.62
BUILDSTDERR:    Compiling sys-info v0.5.8 (/builddir/build/BUILD/sys-info-0.5.8)
BUILDSTDERR:      Running `/usr/bin/rustc --crate-name sys_info lib.rs --color never --emit=dep-info,link -C opt-level=3 --test -C metadata=40e3891ae5ab4945 -C extra-filename=-40e3891ae5ab4945 --out-dir /builddir/build/BUILD/sys-info-0.5.8/target/release/deps -L dependency=/builddir/build/BUILD/sys-info-0.5.8/target/release/deps --extern libc=/builddir/build/BUILD/sys-info-0.5.8/target/release/deps/liblibc-75d467772345d21a.rlib -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now -Ccodegen-units=1 -L native=/builddir/build/BUILD/sys-info-0.5.8/target/release/build/sys-info-ffb149ba0d76c295/out -l static=info`
BUILDSTDERR:     Finished release [optimized] target(s) in 5.34s
BUILDSTDERR:      Running `/builddir/build/BUILD/sys-info-0.5.8/target/release/deps/sys_info-40e3891ae5ab4945 --skip 'test::test_hostname'`
running 9 tests
test test::test_cpu_num ... ok
test test::test_boottime ... ok
test test::test_proc_total ... ok
test test::test_loadavg ... ok
test test::test_os_type ... ok
test test::test_os_release ... ok
test test::test_cpu_speed ... FAILED
test test::test_mem_info ... ok
test test::test_disk_info ... ok
failures:
---- test::test_cpu_speed stdout ----
thread 'test::test_cpu_speed' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
failures:
    test::test_cpu_speed
test result: FAILED. 8 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out
```

```
+ cat /proc/cpuinfo
vendor_id       : IBM/S390
# processors    : 4
bogomips per cpu: 3033.00
max thread id   : 0
features	: esan3 zarch stfle msa ldisp eimm dfp edat etf3eh highgprs te vx sie 
facilities      : 0 1 2 3 4 6 7 8 9 10 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 30 31 32 33 34 35 36 37 40 41 42 43 44 45 47 48 49 50 51 52 53 57 64 69 71 73 74 75 76 77 78 80 81 82 129 131 138
cache0          : level=1 type=Data scope=Private size=128K line_size=256 associativity=8
cache1          : level=1 type=Instruction scope=Private size=96K line_size=256 associativity=6
cache2          : level=2 type=Data scope=Private size=2048K line_size=256 associativity=8
cache3          : level=2 type=Instruction scope=Private size=2048K line_size=256 associativity=8
cache4          : level=3 type=Unified scope=Shared size=65536K line_size=256 associativity=16
cache5          : level=4 type=Unified scope=Shared size=491520K line_size=256 associativity=30
processor 0: version = FF,  identification = 3633E8,  machine = 2964
processor 1: version = FF,  identification = 3633E8,  machine = 2964
processor 2: version = FF,  identification = 3633E8,  machine = 2964
processor 3: version = FF,  identification = 3633E8,  machine = 2964
cpu number      : 0
cpu MHz dynamic : 5000
cpu MHz static  : 5000
cpu number      : 1
cpu MHz dynamic : 5000
cpu MHz static  : 5000
cpu number      : 2
cpu MHz dynamic : 5000
cpu MHz static  : 5000
cpu number      : 3
cpu MHz dynamic : 5000
cpu MHz static  : 5000
+ /usr/bin/env CARGO_HOME=.cargo RUSTC_BOOTSTRAP=1 /usr/bin/cargo test -j4 -Z avoid-dev-deps --release --no-fail-fast -- --skip test::test_hostname
BUILDSTDERR:        Fresh cc v1.0.37
BUILDSTDERR:        Fresh libc v0.2.62
BUILDSTDERR:    Compiling sys-info v0.5.8 (/builddir/build/BUILD/sys-info-0.5.8)
BUILDSTDERR:      Running `/usr/bin/rustc --crate-name sys_info lib.rs --color never --emit=dep-info,link -C opt-level=3 --test -C metadata=1b79dc2e399981f9 -C extra-filename=-1b79dc2e399981f9 --out-dir /builddir/build/BUILD/sys-info-0.5.8/target/release/deps -L dependency=/builddir/build/BUILD/sys-info-0.5.8/target/release/deps --extern libc=/builddir/build/BUILD/sys-info-0.5.8/target/release/deps/liblibc-23d11f1621cb7398.rlib -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now -Ccodegen-units=1 -L native=/builddir/build/BUILD/sys-info-0.5.8/target/release/build/sys-info-81b9f8f9efbeab81/out -l static=info`
BUILDSTDERR:     Finished release [optimized] target(s) in 4.82s
BUILDSTDERR:      Running `/builddir/build/BUILD/sys-info-0.5.8/target/release/deps/sys_info-1b79dc2e399981f9 --skip 'test::test_hostname'`
running 9 tests
test test::test_boottime ... ok
test test::test_cpu_num ... ok
test test::test_loadavg ... ok
test test::test_disk_info ... ok
test test::test_mem_info ... ok
test test::test_os_release ... ok
test test::test_os_type ... ok
test test::test_proc_total ... ok
test test::test_cpu_speed ... FAILED
failures:
---- test::test_cpu_speed stdout ----
thread 'test::test_cpu_speed' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
failures:
    test::test_cpu_speed
test result: FAILED. 8 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out
```

**Comment by ignatenkobrain** [comment]
ppc64le and s390x are fixed with this PR :) Thanks!

**Comment by ignatenkobrain** [comment]
(and no other Fedora architecture broke)

**Pull request merged**
